### PR TITLE
[세키네] vue_axios_code

### PR DESCRIPTION
**Pull request by sknyuki**

### CODE REVIEW

**Comment by sknyuki** [comment]
[게시판예제+3목만들기.pdf](https://github.com/KHWeb19/Homework/files/8224009/%2B3.pdf)

**Comment by sknyuki** [comment]
[EventBus.pdf](https://github.com/KHWeb19/Homework/files/8232974/EventBus.pdf)

**Comment by sknyuki** [comment]
[UI Dialog 정리노트.pdf](https://github.com/KHWeb19/Homework/files/8253581/UI.Dialog.pdf)

**Comment by silenc3502** [comment]
java/test/src/test.java 이 부분 Conflict 해결해주셔야 커밋 가능합니다.

**Pull request closed without merging**
